### ISSUE TITLE
S3 Region not recognised

### ISSUE THREAD

**Issue by marcelteraflow** [rilldata/rill-developer#1577]
**Describe the bug**
S3 regions don't seem to work as expected.

**To Reproduce**
Please see screenshot

**Screenshots**

<img width="517" alt="image" src="https://user-images.githubusercontent.com/116802182/211168258-bf2a26dd-f99e-4c0e-b6c0-246ffa05fe0e.png">

**Desktop (please complete the following information):**
 - OS: Ubuntu 22
 - Browser: Brave
 - Version: 0.18

**Comment by begelundmuller** [comment]
Looks like the artifact being saved from the frontend is:
```yaml
# Visit https://docs.rilldata.com/ to learn more about Rill code artifacts.
type: "s3"
aws.region: "us-east-1"
uri: "s3://dask-data/airline-data/2008.csv"
```
but the backend is expecting the region key to just be `region` (not `aws.region`). 

IIRC, the old connectors used `aws.region`, but the new code files spec had just `region`, so that's probably the reason for the discrepancy.

@magorlick, do you want it to be `region` or `aws.region` in the yaml?
