### ISSUE TITLE
Document artifact templating

### ISSUE THREAD

**Issue by begelundmuller** [rilldata/rill-developer#1817]

**Comment by begelundmuller** [comment]
FYI, the syntax for setting defaults in `rill.yaml` is:

```yaml
compiler: rill-beta
rill_version: next

name: ad-bids

env:
  key1: value1
  key2: value2
```
